services:
  - type: web
    name: telegram-da-net-ne-znayu-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:create_app --host 0.0.0.0 --port 10000 --factory"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
